### ISSUE TITLE
Can't set an email address in cloudflare DNS provider CLOUDFLARE_EMAIL param

### ISSUE THREAD

**Issue by bussyjd** [PalmStoneGames/kube-cert-manager#18]
It's impossible to set an email address in the CLOUDFLARE_EMAIL parameter to set a DNS challenge provider with Cloudflare:

```
The Deployment "kube-cert-manager" is invalid: spec.template.spec.containers[0].env[0].valueFrom.secretKeyRef.key: Invalid value: "foo@bar.com": must match the regex [-._a-zA-Z0-9]+ (e.g. 'key.name' or 'KEY_NAME' or 'key-name')
```

**Comment by luna-duclos** [comment]
Hello,

Could you please share your complete deployment.yaml ?

**Comment by bussyjd** [comment]
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kube-cert-manager
  name: kube-cert-manager
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-cert-manager
      name: kube-cert-manager
    spec:
      containers:
        - name: kube-cert-manager
          image: palmstonegames/kube-cert-manager:0.3.1
          args:
            - "-data-dir=/var/lib/cert-manager"
            - "-acme-url=https://acme-v01.api.letsencrypt.org/directory"
          volumeMounts:
            - name: data
              mountPath: /var/lib/cert-manager
          env:
            - name: CLOUDFLARE_EMAIL
              valueFrom:
                secretKeyRef:
                  name: certsecret
                  key: "foo@bar.com"
            - name: CLOUDFLARE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: certsecret
                  key: XXXXXXXXXXXXXXXXXXXXXXXXXXX
        - name: kubectl-proxy
          image: palmstonegames/kubectl-proxy:1.4.0
      volumes:
        - name: "data"
          gcePersistentDisk:
            pdName: kube-cert-manager
            fsType: ext4
```

Am I doing it wrong?

**Comment by luna-duclos** [comment]
This is not how secrets work, you're supposed to be storing the key and email themselves as a secret within your cluster, and only refer to where they're stored in your secret. See: http://kubernetes.io/docs/user-guide/secrets/#using-secrets-as-environment-variables

For example you could use "email" and "apiKey" as keys, and store the actual email and api key in the secret

**Comment by bussyjd** [comment]
Thank you for the information.
I managed to create a secret and point the deployment.yaml file to the relevant secret keys.
:+1:

**Comment by bussyjd** [comment]
Hello @PSG-Luna 
Thanks again for the help so far.

With deployment.yaml as

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kube-cert-manager
  name: kube-cert-manager
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-cert-manager
      name: kube-cert-manager
    spec:
      containers:
        - name: kubectl-proxy
          image: palmstonegames/kubectl-proxy:1.4.0
        - name: kube-cert-manager
          image: palmstonegames/kube-cert-manager:0.3.1
          args:
            - "-data-dir=/var/lib/cert-manager"
            - "-acme-url=https://acme-v01.api.letsencrypt.org/directory"
          volumeMounts:
            - name: data
              mountPath: /var/lib/cert-manager
          env:
            - name: CLOUDFLARE_EMAIL
              valueFrom:
                secretKeyRef:
                  name: certsecret
                  key: email
            - name: CLOUDFLARE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: certsecret
                  key: apikey
      volumes:
        - name: "data"
          gcePersistentDisk:
            pdName: kube-cert-manager
            fsType: ext4
```

, secret file:

```
apiVersion: v1
kind: Secret
metadata:
  name: certsecret
type: Opaque
data:
  email: xxx
  apikey: yyy=
```

Checked with 
echo "xxx" | base64 -d
foo@bar.com

and certs/mydomain-dot-com.yaml:

```
apiVersion: "stable.k8s.psg.io/v1"
kind: "Certificate"
metadata:
  name: "bar-com"
spec:
  domain: "bar.com"
  email: "foo@bar.com"
  provider: "cloudflare"
```

I get the following error
in the kube-cert-manager logs:

```
2016/10/13 17:09:45 [INFO] acme: Registering account for foo@bar.com
2016/10/13 17:09:45 [INFO][stacktical.com] acme: Obtaining bundled SAN certificate
2016/10/13 17:09:46 [INFO][stacktical.com] acme: Could not find solver for: tls-sni-01
2016/10/13 17:09:46 [INFO][stacktical.com] acme: Could not find solver for: http-01
2016/10/13 17:09:46 [INFO][stacktical.com] acme: Trying to solve DNS-01
2016/10/13 17:09:46 Error while processing certificate event: Error while obtaining certificate for new domain stacktical.com: Error presenting token: Error querying Cloudflare API -> Get https://api.cloudflare.com/client/v4/zones?name=bar.com: net/http: invalid header field value "foo@bar.com\n" for key X-Auth-Email
```

It seems that the `\n` that got its way in the end of the X-Auth-Email header field is the culprit.
I double checked my yaml files and secret string and there is no extra space nor newline.
Any hints?
Thanks
