### ISSUE TITLE
Add support for running per-provider-account kube-cert-manager instances

### ISSUE THREAD

**Issue by whereisaaron** [PalmStoneGames/kube-cert-manager#30]
# Proposal
I propose adding a 'stable.k8s.psg.io/kcm.class' label to allow multiple instances for kube-cert-manager to run in the same namespace(s) for different accounts at the same provider. E.g. if you have two different AWS Route 53 accounts for different domains for Pods that run in the same namespace in your kubernetes cluster. The 'class' could be different accounts for different domains, clients, projects, app, etc.

# Background
One instance of kube-cert-manager can support multiple accounts at different providers, e.g. accounts at route53, cloudflare, and HTTP can used with the same kube-cert-manager instance. The certificate, ingress resources are selected to use different accounts (i.e. at different providers) by the `provider` property or the `stable.k8s.psg.io/kcm.provider` annotation.

However there is no support for two accounts at the same provider, e.g. simpleDNS account X and simpleDNS account Y. The way the [xenolf/lego](https://github.com/xenolf/lego) works with environment variable and files to configure accounts, it is non-trival to support two accounts at the same provider.

A reasonable option is to run an instance of  kube-cert-manager for each account. However, we need a way to partition/filter the certificate/ingress resources so the multiple kube-cert-manager instances don't all try to manage the same resources. This is only possible now if you use a different namespace for each account and use the `-namespaces` command line config to target each certificate/ingress to a different namespace.

A more flexible option would be to add a label that can be used to filter a certificate/ingress/secret to be processed by a particular kube-cert-manager instances. I propose we add a 'class' that partitions certificate/ingress/secret resources. e.g. `class: "AccountX"` or `class: "Client2"` or `class: "MyProject"` or application `class: "MyApp"`.

# Changes Required
Implementing this change requires the following. _Please contribute if I missed something!_
- [x] Add a `stable.k8s.psg.io/kcm.class` label for certificates
- [x] Add a `stable.k8s.psg.io/kcm.class` label for ingresses
- [x] Add optional `-class` command line option
- [x] Add a `stable.k8s.psg.io/kcm.class: <class>` label to any created secrets
- [x] Add a label selector (if -class is set) to the API calls in `getCertificates`, `getIngresses`, `getSecrets`
- [ ] ~~Add a safety check for the class annotation in `gcSecrets`~~ (not necessary)

# Implementation Notes
* If no '-class' is configured, then kube-cert-manager will not filter by class and will not add the class property/annotation to secrets. This will make the class feature backward compatible.
* If both the '-namespaces' and '-class' options are configured, certificates, ingresses, and secrets will be filtered by namespace first, and class second. So for namespace-targeted instances, it will be possible to use the same or different accounts for the same class in different namespaces.

**Comment by whereisaaron** [comment]
The Kubernetes API only support filtering by labels and not by annotations. Therefore any information to be used for filtering should be a label. E.g. it's silly to suck down and monitor a million Secrets in a large cluster if only 100 are certificate Secrets for our certificate manager instance. App [labels can and should be prefixed](https://kubernetes.io/docs/user-guide/labels/#syntax-and-character-set) just like annotations. I am changing the `kcm.class` to be a label. I think `kcm.enabled` should have been a label too. `kcm.provider` and `kcm.email` seem appropriate an annotations.

## Certificate sample
```
apiVersion: stable.k8s.psg.io/v1
kind: Certificate
metadata:
  name: foo-test
  label:
    stable.k8s.psg.io/kcm.class: "aws-account-1"
spec:
  domain: "foo.vpc.deviate.net.nz"
  email: "test@example.com"
  provider: "route53"
  secretName: "foo-test-cert"
```

## Partial ingress sample
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  label:
    stable.k8s.psg.io/kcm.class: "aws-account-1"
  annotations:
    stable.k8s.psg.io/kcm.enabled: "true"
    stable.k8s.psg.io/kcm.provider: "route53"
    stable.k8s.psg.io/kcm.email: "test@example.com"
spec:
...
```

**Comment by luna-duclos** [comment]
This all looks good to me, I'd also be provisionally in favor of moving kcm.enabled to a label so it can be correctly filtered on, as long as we also still respect the annotation if it's there (With the label taking priority if both are present).

I would absolutely merge a PR that follows this design

**Comment by whereisaaron** [comment]
I have completed and lightly tested an implementation of the `-class` feature. I also added `-default-provider` and `-default-email` options. This means that Certificates for a kcm instance that is for one provider account can be minimally expressed as below. With the ability to override the default provider, email, and secret name if you wish.
```
apiVersion: stable.k8s.psg.io/v1
kind: Certificate
metadata:
  name: foo-test
  labels:
    stable.k8s.psg.io/kcm.class: "aws-account-1"
spec:
  domain: "foo.vpc.deviate.net.nz"
```
The `-class` feature is backwards compatible. If you do not specify it, all Certificates/Ingresses in the configured namespace(s) will be watched as before. If you do specify it, the label means the kcm instance does not waste any time processing resources and events except for its own labelled resources. The improves scaling when you have lots of Secrets that aren't for kcm.

If you do specify `-class` then the `stable.k8s.psg.io/kcm.enabled: "true"` annotation is deprecated, it will be ignored on Certificate and Ingresses, and it will not be added to Secrets (the `stable.k8s.psg.io/kcm.class` label is added instead).

I have changed the label added to Secrets from `domain` to `stable.k8s.psg.io/kcm.domain`. Un-prefixed labels and annotation are only for end users I read in the k8s doc, k8s services are always supposed to prefix their annotations and labels. This is backwards compatible, existing Secrets will have the label upgraded on the next renewal.

The code is on my ['class' branch](https://github.com/whereisaaron/kube-cert-manager/tree/class) but no need to look at it until I test and groom it a lot more.
