### ISSUE TITLE
No activity after adding ingress with annotations

### ISSUE THREAD

**Issue by mavnn** [PalmStoneGames/kube-cert-manager#34]
I've deployed kube-cert-manager, but nothing appears to happen when I then create a tagged ingress resource. Is there anyway I can debug further what is happening?

The ingress looks like this:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    stable.k8s.psg.io/kcm.enabled: "true"
    stable.k8s.psg.io/kcm.provider: "rfc2136"
    stable.k8s.psg.io/kcm.email: "hi@<mydomain>"
spec:
  tls:
    - hosts:
      - <mydomain>
      - i.<mydomain>
      secretName: tls
  rules:
  <some rules here that seem to work>
```

The kube-cert-manager deploy looks like this:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kube-cert-manager
  name: kube-cert-manager
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-cert-manager
      name: kube-cert-manager
    spec:
      containers:
        - name: kube-cert-manager
          image: palmstonegames/kube-cert-manager:0.3.1
          args:
            - "-data-dir=/var/lib/cert-manager"
            - "-acme-url=https://acme-staging.api.letsencrypt.org/directory"
            # NOTE: the URL above points to the staging server, where you won't get real certs.
            # Uncomment the line below to use the production LetsEncrypt server:
            #- "-acme-url=https://acme-v01.api.letsencrypt.org/directory"
          env:
          - name: RFC2136_NAMESERVER
            value: <nameserver>
          - name: RFC2136_TSIG_KEY
            value: <tsig_key>
          - name: RFC2136_TSIG_SECRET
            value: <tsig_secret>
          volumeMounts:
            - name: data
              mountPath: /var/lib/cert-manager
        - name: kubectl-proxy
          image: palmstonegames/kubectl-proxy:1.4.0
      volumes:
        - name: "data"
          persistentVolumeClaim:
            claimName: certs
```

Logs from the kube-cert-manager pod:

```
 2017-01-18T11:47:44.348529154Z 2017/01/18 11:47:44 Starting Kubernetes Certificate Controller...
2017-01-18T11:47:44.348653419Z 2017/01/18 11:47:44 Kubernetes Certificate Controller started successfully.
2017-01-18T11:47:44.349468788Z 2017/01/18 11:47:44 Error while watching kubernetes events: Get http://127.0.0.1:8001/apis/extensions/v1beta1/ingresses?watch=true&resourceVersion=0: dial tcp 127.0.0.1:8001: getsockopt: connection refused
2017-01-18T11:47:44.349595320Z 2017/01/18 11:47:44 Error while watching kubernetes events: Get http://127.0.0.1:8001/apis/stable.k8s.psg.io/v1/certificates?watch=true&resourceVersion=0: dial tcp 127.0.0.1:8001: getsockopt: connection refused 
```
and then nothing, which I understand to be normal.

**Comment by mavnn** [comment]
I have configured the ingress to run in a namespace, if that would make any difference.

**Comment by luna-duclos** [comment]
Is KCM configured to monitor the same namespace ?

**Comment by mavnn** [comment]
Hi Luna,
KCM is deployed in the same namespace - I had assumed that was the
namespace it would watch given that's how certificates seem to function.
I'll check the config options more thoroughly!

Thanks

**Comment by luna-duclos** [comment]
It indeed SHOULD be, but there might be a bug ... Please let me know

**Comment by whereisaaron** [comment]
@mavnn it is probably not working because you have multiple domains for one Secret, which kcm does not support. If you check the logs for the kcm container you'll probably see the warnings about this (`kubectl logs podname -c kube-cert-manager`)
```
  tls:
    - hosts:
      - <mydomain>
      - i.<mydomain>
      secretName: tls
```
Change it to two secrets as below and you should be away. You'll get two certificates, one for each domain name, but that will work perfectly with the Ingress.
```
  tls:
    - hosts:
      - <mydomain>
      secretName: tls1
    - hosts:
      - i.<mydomain>
      secretName: tls2
```
