### ISSUE TITLE
Use an Ingress to route and automatically handle HTTP challenges

### ISSUE THREAD

**Issue by whereisaaron** [PalmStoneGames/kube-cert-manager#42]
I use an instance 'kube-cert-manager' with the `class: http` to handle HTTP challenges. I route the challenges to 'kube-cert-manager' by adding a proxy to the template for Ingresses in the nginx ingress controller template (sample patch an for nginx-ingress v0.8.3 is below).

This works great and it can even process requests when an Ingress is password-protected or IP-restricted. The only hitch is if the kube-cert-manager Service DNS name does not exist then nginx won't reload properly until the DNS name appears.

While this works fine, [`kube-lego`](https://github.com/jetstack/kube-lego) handles HTTP challenges an even better way by using an Ingress of its own to add domains it is processing challenges for, just routing the challenge path to itself. This is possible because the ingress controller supports multiple Ingresses specifying the same domain name. `kube-lego` adds the domain for the challenge path to its own Ingress, waits until nginx-ingress reconfigures and then completes the challenge.

https://github.com/jetstack/kube-lego/blob/master/pkg/provider/nginx/nginx.go#L94-L130

We should consider this approach for HTTP challenges for kube-cert-manager.

BTW, comparing `kube-lego` with `kube-cert-manager`:
- `kube-lego` is good for HTTP challenges but doesn't handle DNS challenges or DNS API's
- `kube-lego` only works with Ingresses, `kube-cert-manager` Certficate resource can get DNS challenge certificates for non-website purposes (e.g. email or LDAP servers)
- `kube-lego` code has a mock and test framework, `kube-cert-manager` has no tests

```
*** 194,203 ****
--- 194,208 ----
          more_set_headers                            "Strict-Transport-Security: max-age={{ $cfg.hstsMaxAge }}{{ if $cfg.hstsIncludeSubdomains }}; includeSubDomains{{ end }}; preload";
          {{- end }}
  
          {{ if $cfg.enableVtsStatus }}vhost_traffic_status_filter_by_set_key $geoip_country_code country::$server_name;{{ end }}
  
+         location /.well-known/acme-challenge {
+             proxy_set_header Host $host;
+             proxy_pass http://kube-cert-manager-http.ingress.svc.cluster.local;
+         }
+ 
          {{- range $location := $server.Locations }}
          {{ $path := buildLocation $location }}
          location {{ $path }} {
              {{ if gt (len $location.Whitelist.CIDR) 0 }}
              {{- range $ip := $location.Whitelist.CIDR }}
```

```
...
        volumeMounts:
          - mountPath: /etc/nginx/template
            name: nginx-template-volume
            readOnly: true
      volumes:
        - name: nginx-template-volume
          configMap:
            name: nginx-ingress-template
            items:
            - key: nginx.tmpl
              path: nginx.tmpl
```
