### ISSUE TITLE
kube-cert-manager not listening on port 8080 for HTTP challenges

### ISSUE THREAD

**Issue by ferrerluis** [PalmStoneGames/kube-cert-manager#79]
I am using v0.3.1 of `kube-cert-manager` and running GKE on a 1.6.4 k8s cluster.

When I set up my ingress to proxy requests from `/.well-known/acme-challenge/*` to my `kube-cert-manager-service` and create a new certificate, LetsEncrypt fails to communicate with the server and find the challenge.

On the [Providers Section](https://github.com/PalmStoneGames/kube-cert-manager/blob/v0.3.1/docs/providers.md) of the docs, it says that you have to route all connections from `/.well-known/acme-challenge/` to the port 8080 for `kube-cert-manager`.

These are my k8s files:

**Deployment**
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kube-cert-manager
  name: kube-cert-manager
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-cert-manager
      name: kube-cert-manager
    spec:
      containers:
        - name: kube-cert-manager
          image: palmstonegames/kube-cert-manager:0.3.1
          args:
            - "-data-dir=/var/lib/cert-manager"
            - "-acme-url=https://acme-staging.api.letsencrypt.org/directory"
          volumeMounts:
            - name: data
              mountPath: /var/lib/cert-manager
        - name: kubectl-proxy
          image: palmstonegames/kubectl-proxy:1.4.0
      volumes:
        - name: "data"
          gcePersistentDisk:
            pdName: kube-cert-manager
            fsType: ext4
```

**Service**
```yaml
apiVersion: v1
kind: Service
metadata:
  name: kube-cert-manager-service
spec:
  selector:
    app: kube-cert-manager
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
```

**Ingress**
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cachet-stage-ingress
  annotations:
    stable.k8s.psg.io/kcm.enabled: "true"
    stable.k8s.psg.io/kcm.provider: "http"
    stable.k8s.psg.io/kcm.email: "lferrer@example.com"
    kubernetes.io/ingress.global-static-ip-name: "cachet-stage-ip"
    kubernetes.io/ingress.class: "gce"
spec:
  # tls:
  # - hosts:
  #   - status-stage.example.com
  #   secretName: status-stage.example.com
  rules:
  - host: "status-stage.example.com"
    http:
      paths:
      - path: /.well-known/acme-challenge/*
        backend:
          serviceName: kube-cert-manager-service
          servicePort: http
  backend:
      serviceName: cachet-stage-service
      servicePort: http
```
