### ISSUE TITLE
If someone specifies a bad secret name, kube-cert-manager eats up all of the ratelimit

### ISSUE THREAD

**Issue by mikebryant** [PalmStoneGames/kube-cert-manager#81]
e.g.
```
- apiVersion: stable.k8s.psg.io/v1
  kind: Certificate
  spec:
    secretName: blah_api
```

`kube-cert-manager` can't create the `Secret`, so it just loops, repeatedly requesting the certificate but failing to store it anywhere, so it uses up all of the LetsEncrypt rate limit

If it's given a secret with an invalid name, it needs to either not process the object, or at least save the certificate and not request it repeatedly in a tight loop
